[package]
name = "wallmeter"
version = "0.1.0"
edition = "2021"

[dependencies]
notify = "7.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
whoami = "1.2"
notify-rust = "4"
tray-icon = "0.19.2"
